

FROM ghcr.io/pnpm/pnpm:11
RUN pnpm runtime set node 22 -g

WORKDIR /usr/src/app

ARG DATABASE_URL
COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY .npmrc .npmrc
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/ws-backend ./apps/ws-backend

RUN pnpm install 
RUN  DATABASE_URL=${DATABASE_URL} pnpm run db:generate

EXPOSE 8080

CMD [ "pnpm","run","start:ws" ]